project:
  type: website
  output-dir: "."

website:
  title: "Grey Shield Research LLC"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: publications.qmd
        text: Publications
      - href: services.qmd
        text: Services
      - href: FAQ.qmd
        text: FAQ        
      - href: Contact_Us.qmd
        text: Contact Us

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

