---
title: "Grey Shield Research LLC"
---

*Corrections Data, Made Useful* is not just our slogan — it’s our mission. We aim to empower correctional organizations with actionable insights for more informed decisions, using the best data and analytics available. Assisting correctional and pre-trial agencies, along with courts, is our passion.  

We offer:

- Basic and advanced data analytics specifically tailored to corrections.
- Data services designed to meet PREA, the Jail Reimbursement Act\*, or other correctional reporting requirements.
- Budget-friendly options for smaller agencies.
- Top-notch data security to ensure the privacy of your data.

Together, we can make corrections safer and more effective for officers, inmates, and communities.

Whether you manage a prison, jail, lockup, pre-trial services agency, or other law enforcement organization, we offer a variety of services to fit your needs. Whether you’re seeking complex, long-term data analyses or simple descriptive statistics to meet your reporting obligations, we can work within your budget to produce high-quality reports and studies.

Be sure to check out our Publications section, and if you have any questions about how we can help your organization, please feel free to contact us.

<span class="footnote-text">*Applicable in New Mexico.</span>
